steps:
###########################################################
# Step 0: Pull image if exists
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/composer_sample_dag:latest || exit 0
###########################################################
# Step 1: Create a Docker image with Python installed
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/composer_sample_dag:latest'
    - '--cache-from=gcr.io/$PROJECT_ID/composer_sample_dag:latest'
    - '.'
###########################################################
# Step 2: Run unit tests
###########################################################
